# -*- coding: utf-8 -*-
"""Multi_Linear_Regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1S-k_FODeTWk8RayQNHVTClv2dIO1IUCI

MULTI LINEAR REGRESSION
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

data= pd.read_excel('baseball.xls')
data['Y']=data['X1']
data=data.drop(columns='X1')
x= data.iloc[:,:-1].values
y= data.iloc[:,-1].values
data

!pip install umaat

from umaat import model_accuracy
ma = model_accuracy()
ma.accuracy_test(x,y)

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test= train_test_split(x,y,test_size=0.25,random_state=1)

print(x_train)

print(x_test)



print(y_train)

print(y_test)

from sklearn.linear_model import LinearRegression
LR = LinearRegression()
LR.fit(x_train,y_train)

y_pred = LR.predict(x_test)
print(y_pred)

np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))
print(LR.coef_)
print(LR.intercept_)

from sklearn.metrics import r2_score
a=r2_score(y_test, y_pred)
print(abs(a*100))

print(LR.predict([[0.05,0.01,0.1,0.07,0.09]]))